/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.pojos;


import com.technokratos.model.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * Аккаунт
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private String password;
    private String email;

    public AccountEntity() {}

    public AccountEntity(AccountEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.password = value.password;
        this.email = value.email;
    }

    public AccountEntity(
        UUID id,
        String name,
        String password,
        String email
    ) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.email = email;
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.account.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.account.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.account.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.account.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>public.account.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.account.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountEntity other = (AccountEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
