/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.pojos;


import com.technokratos.model.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AwardEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID lotId;
    private UUID accountId;

    public AwardEntity() {}

    public AwardEntity(AwardEntity value) {
        this.id = value.id;
        this.lotId = value.lotId;
        this.accountId = value.accountId;
    }

    public AwardEntity(
        UUID id,
        UUID lotId,
        UUID accountId
    ) {
        this.id = id;
        this.lotId = lotId;
        this.accountId = accountId;
    }

    /**
     * Getter for <code>public.award.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.award.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.award.lot_id</code>.
     */
    public UUID getLotId() {
        return this.lotId;
    }

    /**
     * Setter for <code>public.award.lot_id</code>.
     */
    public void setLotId(UUID lotId) {
        this.lotId = lotId;
    }

    /**
     * Getter for <code>public.award.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>public.award.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AwardEntity other = (AwardEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.lotId == null) {
            if (other.lotId != null)
                return false;
        }
        else if (!this.lotId.equals(other.lotId))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.lotId == null) ? 0 : this.lotId.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AwardEntity (");

        sb.append(id);
        sb.append(", ").append(lotId);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
