/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.pojos;


import com.technokratos.model.Entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;


/**
 * Ставка
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BetEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private BigDecimal amount;
    private LocalDate dateTime;
    private UUID lotId;
    private UUID accountId;

    public BetEntity() {}

    public BetEntity(BetEntity value) {
        this.id = value.id;
        this.amount = value.amount;
        this.dateTime = value.dateTime;
        this.lotId = value.lotId;
        this.accountId = value.accountId;
    }

    public BetEntity(
        UUID id,
        BigDecimal amount,
        LocalDate dateTime,
        UUID lotId,
        UUID accountId
    ) {
        this.id = id;
        this.amount = amount;
        this.dateTime = dateTime;
        this.lotId = lotId;
        this.accountId = accountId;
    }

    /**
     * Getter for <code>public.bet.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.bet.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.bet.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.bet.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.bet.date_time</code>.
     */
    public LocalDate getDateTime() {
        return this.dateTime;
    }

    /**
     * Setter for <code>public.bet.date_time</code>.
     */
    public void setDateTime(LocalDate dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * Getter for <code>public.bet.lot_id</code>.
     */
    public UUID getLotId() {
        return this.lotId;
    }

    /**
     * Setter for <code>public.bet.lot_id</code>.
     */
    public void setLotId(UUID lotId) {
        this.lotId = lotId;
    }

    /**
     * Getter for <code>public.bet.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>public.bet.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BetEntity other = (BetEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.dateTime == null) {
            if (other.dateTime != null)
                return false;
        }
        else if (!this.dateTime.equals(other.dateTime))
            return false;
        if (this.lotId == null) {
            if (other.lotId != null)
                return false;
        }
        else if (!this.lotId.equals(other.lotId))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.dateTime == null) ? 0 : this.dateTime.hashCode());
        result = prime * result + ((this.lotId == null) ? 0 : this.lotId.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BetEntity (");

        sb.append(id);
        sb.append(", ").append(amount);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(lotId);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
