/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.pojos;


import com.technokratos.model.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * Лот
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LotEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private String description;
    private String artikul;
    private String status;
    private UUID auctionId;

    public LotEntity() {}

    public LotEntity(LotEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.artikul = value.artikul;
        this.status = value.status;
        this.auctionId = value.auctionId;
    }

    public LotEntity(
        UUID id,
        String name,
        String description,
        String artikul,
        String status,
        UUID auctionId
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.artikul = artikul;
        this.status = status;
        this.auctionId = auctionId;
    }

    /**
     * Getter for <code>public.lot.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.lot.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.lot.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.lot.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.lot.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.lot.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.lot.artikul</code>.
     */
    public String getArtikul() {
        return this.artikul;
    }

    /**
     * Setter for <code>public.lot.artikul</code>.
     */
    public void setArtikul(String artikul) {
        this.artikul = artikul;
    }

    /**
     * Getter for <code>public.lot.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.lot.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.lot.auction_id</code>.
     */
    public UUID getAuctionId() {
        return this.auctionId;
    }

    /**
     * Setter for <code>public.lot.auction_id</code>.
     */
    public void setAuctionId(UUID auctionId) {
        this.auctionId = auctionId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LotEntity other = (LotEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.artikul == null) {
            if (other.artikul != null)
                return false;
        }
        else if (!this.artikul.equals(other.artikul))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.auctionId == null) {
            if (other.auctionId != null)
                return false;
        }
        else if (!this.auctionId.equals(other.auctionId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.artikul == null) ? 0 : this.artikul.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.auctionId == null) ? 0 : this.auctionId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LotEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(artikul);
        sb.append(", ").append(status);
        sb.append(", ").append(auctionId);

        sb.append(")");
        return sb.toString();
    }
}
