/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables;


import com.technokratos.model.jooq.schema.Keys;
import com.technokratos.model.jooq.schema.Public;
import com.technokratos.model.jooq.schema.tables.records.AuctionRecord;

import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Аукцион
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auction extends TableImpl<AuctionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auction</code>
     */
    public static final Auction AUCTION_ENTITY = new Auction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuctionRecord> getRecordType() {
        return AuctionRecord.class;
    }

    /**
     * The column <code>public.auction.id</code>.
     */
    public final TableField<AuctionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.auction.name</code>.
     */
    public final TableField<AuctionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.auction.account_id</code>.
     */
    public final TableField<AuctionRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.auction.status</code>.
     */
    public final TableField<AuctionRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(10).nullable(false).defaultValue(DSL.field("'open'::character varying", SQLDataType.VARCHAR)), this, "");

    private Auction(Name alias, Table<AuctionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Auction(Name alias, Table<AuctionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Аукцион"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.auction</code> table reference
     */
    public Auction(String alias) {
        this(DSL.name(alias), AUCTION_ENTITY);
    }

    /**
     * Create an aliased <code>public.auction</code> table reference
     */
    public Auction(Name alias) {
        this(alias, AUCTION_ENTITY);
    }

    /**
     * Create a <code>public.auction</code> table reference
     */
    public Auction() {
        this(DSL.name("auction"), null);
    }

    public <O extends Record> Auction(Table<O> child, ForeignKey<O, AuctionRecord> key) {
        super(child, key, AUCTION_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AuctionRecord> getPrimaryKey() {
        return Keys.AUCTION_PK;
    }

    @Override
    public Auction as(String alias) {
        return new Auction(DSL.name(alias), this);
    }

    @Override
    public Auction as(Name alias) {
        return new Auction(alias, this);
    }

    @Override
    public Auction as(Table<?> alias) {
        return new Auction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Auction rename(String name) {
        return new Auction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auction rename(Name name) {
        return new Auction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auction rename(Table<?> name) {
        return new Auction(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, UUID, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super UUID, ? super String, ? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super UUID, ? super String, ? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
