/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables;


import com.technokratos.model.jooq.schema.Keys;
import com.technokratos.model.jooq.schema.Public;
import com.technokratos.model.jooq.schema.tables.records.AwardRecord;

import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Award extends TableImpl<AwardRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.award</code>
     */
    public static final Award AWARD_ENTITY = new Award();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AwardRecord> getRecordType() {
        return AwardRecord.class;
    }

    /**
     * The column <code>public.award.id</code>.
     */
    public final TableField<AwardRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.award.lot_id</code>.
     */
    public final TableField<AwardRecord, UUID> LOT_ID = createField(DSL.name("lot_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.award.account_id</code>.
     */
    public final TableField<AwardRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    private Award(Name alias, Table<AwardRecord> aliased) {
        this(alias, aliased, null);
    }

    private Award(Name alias, Table<AwardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.award</code> table reference
     */
    public Award(String alias) {
        this(DSL.name(alias), AWARD_ENTITY);
    }

    /**
     * Create an aliased <code>public.award</code> table reference
     */
    public Award(Name alias) {
        this(alias, AWARD_ENTITY);
    }

    /**
     * Create a <code>public.award</code> table reference
     */
    public Award() {
        this(DSL.name("award"), null);
    }

    public <O extends Record> Award(Table<O> child, ForeignKey<O, AwardRecord> key) {
        super(child, key, AWARD_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AwardRecord> getPrimaryKey() {
        return Keys.AWARD_PK;
    }

    @Override
    public Award as(String alias) {
        return new Award(DSL.name(alias), this);
    }

    @Override
    public Award as(Name alias) {
        return new Award(alias, this);
    }

    @Override
    public Award as(Table<?> alias) {
        return new Award(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Award rename(String name) {
        return new Award(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Award rename(Name name) {
        return new Award(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Award rename(Table<?> name) {
        return new Award(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
