/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema;


import com.technokratos.model.jooq.schema.tables.Account;
import com.technokratos.model.jooq.schema.tables.Auction;
import com.technokratos.model.jooq.schema.tables.Award;
import com.technokratos.model.jooq.schema.tables.Bet;
import com.technokratos.model.jooq.schema.tables.Lot;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Аккаунт
     */
    public final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * Аукцион
     */
    public final Auction AUCTION_ENTITY = Auction.AUCTION_ENTITY;

    /**
     * The table <code>public.award</code>.
     */
    public final Award AWARD_ENTITY = Award.AWARD_ENTITY;

    /**
     * Ставка
     */
    public final Bet BET_ENTITY = Bet.BET_ENTITY;

    /**
     * Лот
     */
    public final Lot LOT_ENTITY = Lot.LOT_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT_ENTITY,
            Auction.AUCTION_ENTITY,
            Award.AWARD_ENTITY,
            Bet.BET_ENTITY,
            Lot.LOT_ENTITY
        );
    }
}
