/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema;


import com.technokratos.model.jooq.schema.tables.Account;
import com.technokratos.model.jooq.schema.tables.Auction;
import com.technokratos.model.jooq.schema.tables.Award;
import com.technokratos.model.jooq.schema.tables.Bet;
import com.technokratos.model.jooq.schema.tables.Lot;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Аккаунт
     */
    public static final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * Аукцион
     */
    public static final Auction AUCTION_ENTITY = Auction.AUCTION_ENTITY;

    /**
     * The table <code>public.award</code>.
     */
    public static final Award AWARD_ENTITY = Award.AWARD_ENTITY;

    /**
     * Ставка
     */
    public static final Bet BET_ENTITY = Bet.BET_ENTITY;

    /**
     * Лот
     */
    public static final Lot LOT_ENTITY = Lot.LOT_ENTITY;
}
